---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artfordapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: artfordapp
  template:
    metadata:
      labels:
        app: artfordapp
    spec:
      containers:
      - name: artford-con
        image: artford7174/vmtechnologies-devops-1:05032025-1238
        ports:
        - containerPort: 8080

---
#Service Type NodePort
apiVersion: v1
kind: Service
metadata:
  name: artfordapp
  labels: 
    app: artfordapp
spec:
  selector:
    app: artfordapp
  type: NodePort
  ports:
  - name: http
    nodePort: 30100
    port: 8080
    targetPort: 8080
