---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artford-app
  labels:
    app: artford-app
spec:
 replicas: 4
 selector:
   matchLabels:
     app: artford-app
 template:
   metadata:
     labels:
       app: artford-app
   spec:
     containers:
     - name: dann-con
       image: mobanntechnologies/july24:{{build_number}}
       ports:
       - containerPort: 8080

---
#Service Type nodePort
apiVersion: v1
kind: Service
metadata:
  name: artford-app
  labels:
    app: artford-app
spec:
  selector:
    app: artford-app
  type: NodePort
  ports:
  - nodePort: 30100
    port: 8080
    targetPort: 8080
